// Mock Data สำหรับทดสอบ Frontend โดยไม่ต้องใช้ Backend จริง

import { Product, LightingPool, ClearanceProduct, User } from '@/types';

// ข้อมูลสินค้าตัวอย่าง
export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Modern Pendant Light - Industrial Style",
    description: "โคมไฟแขวนสไตล์อินดัสเทรียล ออกแบบสวยงาม เหมาะสำหรับห้องนั่งเล่น ห้องครัว หรือบาร์ โครงเหล็กคุณภาพสูง ทนทานแข็งแรง",
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1543198126-a8ad0a37d7e8?w=800&h=800&fit=crop",
    ],
    retailPrice: 1590,
    contractorPrice: 890,
    factoryPrice: 990,
    category: "Pendant Lights",
    subcategory: "Industrial",
    rating: 4.8,
    reviews: 124,
    inStock: true,
    stockQuantity: 45,
    hasPool: true,
    poolPrice: 890,
    specifications: [
      { name: "กำลังไฟ", value: "60W" },
      { name: "วัสดุ", value: "เหล็กชุบโครเมียม" },
      { name: "ขนาด", value: "30cm x 30cm x 40cm" },
      { name: "หลอดไฟ", value: "E27 (ไม่รวมหลอด)" },
      { name: "สี", value: "ดำ, เงิน" },
      { name: "การรับประกัน", value: "5 ปี" },
    ],
    features: [
      "ปรับแสงได้ (Dimmable)",
      "ประหยัดพลังงาน",
      "ง่ายต่อการติดตั้ง",
      "เหมาะกับเพดานสูง 2.5-3.5 เมตร",
    ],
  },
  {
    id: 2,
    name: "Crystal Chandelier 6-Light",
    description: "โคมระย้าคริสตัล 6 แขน หรูหรา สง่างาม เหมาะสำหรับห้องรับแขก ห้องทานอาหาร หรือโรงแรม คริสตัลแท้นำเข้า ส่องแสงสวยงาม",
    image: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=800&fit=crop",
    ],
    retailPrice: 4590,
    contractorPrice: 2690,
    factoryPrice: 2990,
    category: "Chandeliers",
    subcategory: "Crystal",
    rating: 4.9,
    reviews: 89,
    inStock: true,
    stockQuantity: 18,
    hasPool: true,
    poolPrice: 2690,
    specifications: [
      { name: "กำลังไฟ", value: "360W (60W x 6)" },
      { name: "วัสดุ", value: "คริสตัลแท้ + โลหะชุบทอง" },
      { name: "ขนาด", value: "60cm x 60cm x 80cm" },
      { name: "จำนวนหลอด", value: "6 หลอด E14" },
      { name: "น้ำหนัก", value: "8.5 กก." },
      { name: "การรับประกัน", value: "5 ปี" },
    ],
    features: [
      "คริสตัลแท้ K9 นำเข้า",
      "โครงโลหะชุบทองคุณภาพสูง",
      "ส่องแสงสวยงามทุกมุม",
      "พร้อมอุปกรณ์ติดตั้งครบชุด",
    ],
  },
  {
    id: 3,
    name: "LED Track Lighting System",
    description: "ระบบไฟ Track LED แบบครบชุด เหมาะสำหรับร้านค้า ห้องแสดงสินค้า หรือออฟฟิศ ปรับทิศทางได้ 360 องศา ประหยัดไฟ",
    image: "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&h=800&fit=crop",
    ],
    retailPrice: 2490,
    contractorPrice: 1490,
    factoryPrice: 1690,
    category: "Track Lighting",
    subcategory: "LED",
    rating: 4.7,
    reviews: 156,
    inStock: true,
    stockQuantity: 67,
    hasPool: true,
    poolPrice: 1490,
    specifications: [
      { name: "ความยาวราง", value: "1 เมตร (ต่อได้)" },
      { name: "จำนวนหลอด", value: "4 หลอด LED" },
      { name: "กำลังไฟต่อหลอด", value: "7W" },
      { name: "สีแสง", value: "Warm White 3000K" },
      { name: "อายุการใช้งาน", value: "50,000 ชั่วโมง" },
      { name: "การรับประกัน", value: "3 ปี" },
    ],
    features: [
      "ปรับมุมได้ 360 องศา",
      "ประหยัดไฟถึง 80%",
      "แสงสว่างสม่ำเสมอ",
      "ติดตั้งง่าย ไม่ต้องเจาะเพดาน",
    ],
  },
  {
    id: 4,
    name: "Outdoor Wall Sconce - Set of 2",
    description: "โคมไฟติดผนังภายนอก กันน้ำ IP65 ชุดละ 2 ชิ้น เหมาะสำหรับทางเดิน ระเบียง หรือสวน ทนทานต่อสภาพอากาศ",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=800&fit=crop",
    ],
    retailPrice: 1290,
    contractorPrice: 690,
    factoryPrice: 790,
    category: "Outdoor Lighting",
    subcategory: "Wall Sconce",
    rating: 4.6,
    reviews: 203,
    inStock: true,
    stockQuantity: 89,
    hasPool: false,
    specifications: [
      { name: "กันน้ำ", value: "IP65" },
      { name: "วัสดุ", value: "อลูมิเนียมกันสนิม" },
      { name: "กำลังไฟ", value: "12W LED" },
      { name: "ขนาด", value: "15cm x 30cm" },
      { name: "สีแสง", value: "Warm White" },
      { name: "การรับประกัน", value: "2 ปี" },
    ],
    features: [
      "กันน้ำกันฝุ่น IP65",
      "วัสดุกันสนิม ทนทาน",
      "ใช้งานกลางแจ้งได้",
      "มาพร้อมหลอด LED ในชุด",
    ],
  },
  {
    id: 5,
    name: "Smart LED Ceiling Light",
    description: "โคมไฟเพดาน LED อัจฉริยะ ควบคุมผ่านมือถือ ปรับความสว่างและสีแสงได้ เหมาะสำหรับห้องนอน ห้องนั่งเล่น",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&h=800&fit=crop",
    ],
    retailPrice: 3290,
    contractorPrice: 1890,
    factoryPrice: 2090,
    category: "Ceiling Lights",
    subcategory: "Smart",
    rating: 4.8,
    reviews: 167,
    inStock: true,
    stockQuantity: 34,
    hasPool: false,
    specifications: [
      { name: "กำลังไฟ", value: "36W LED" },
      { name: "ขนาด", value: "45cm เส้นผ่านศูนย์กลาง" },
      { name: "การควบคุม", value: "WiFi + Remote" },
      { name: "สีแสง", value: "RGB + Warm/Cool White" },
      { name: "App", value: "Smart Life / Tuya" },
      { name: "การรับประกัน", value: "3 ปี" },
    ],
    features: [
      "ควบคุมผ่าน WiFi และ Remote",
      "ปรับความสว่าง 1-100%",
      "เปลี่ยนสีแสงได้หลากหลาย",
      "รองรับ Alexa และ Google Home",
    ],
  },
  {
    id: 6,
    name: "Vintage Edison Bulb Pendant",
    description: "โคมไฟแขวนสไตล์วินเทจ พร้อมหลอด Edison สวยงาม เหมาะสำหรับคาเฟ่ ร้านอาหาร หรือบ้านสไตล์ลอฟท์",
    image: "https://images.unsplash.com/photo-1550785085-a6d5dd86c25f?w=800&h=800&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1550785085-a6d5dd86c25f?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&h=800&fit=crop",
    ],
    retailPrice: 1890,
    contractorPrice: 990,
    factoryPrice: 1190,
    category: "Pendant Lights",
    subcategory: "Vintage",
    rating: 4.9,
    reviews: 234,
    inStock: true,
    stockQuantity: 23,
    hasPool: false,
    onClearance: true,
    clearancePrice: 890,
    specifications: [
      { name: "วัสดุ", value: "ทองเหลืองรมดำ" },
      { name: "ขนาด", value: "20cm x 20cm x 35cm" },
      { name: "หลอดไฟ", value: "E27 Edison 40W (รวมในชุด)" },
      { name: "สายไฟ", value: "ปรับความยาวได้ 1.5 เมตร" },
      { name: "สไตล์", value: "Vintage Industrial" },
      { name: "การรับประกัน", value: "2 ปี" },
    ],
    features: [
      "หลอด Edison Filament แท้",
      "สายไฟแบบถัก สวยงาม",
      "โครงทองเหลืองคุณภาพสูง",
      "สร้างบรรยากาศวินเทจ",
    ],
  },
];

// Mock Lighting Pools
export const mockPools: LightingPool[] = [
  {
    id: 1,
    productId: 1,
    product: mockProducts[0],
    targetParticipants: 12,
    currentParticipants: 8,
    poolPrice: 890,
    startDate: new Date('2024-12-13T10:00:00Z'),
    endDate: new Date('2024-12-15T18:00:00Z'),
    status: 'active',
  },
  {
    id: 2,
    productId: 2,
    product: mockProducts[1],
    targetParticipants: 24,
    currentParticipants: 15,
    poolPrice: 2690,
    startDate: new Date('2024-12-12T10:00:00Z'),
    endDate: new Date('2024-12-14T18:00:00Z'),
    status: 'active',
  },
  {
    id: 3,
    productId: 3,
    product: mockProducts[2],
    targetParticipants: 6,
    currentParticipants: 4,
    poolPrice: 1490,
    startDate: new Date('2024-12-11T10:00:00Z'),
    endDate: new Date('2024-12-17T18:00:00Z'),
    status: 'active',
  },
];

// Mock Clearance Products
export const mockClearanceProducts: ClearanceProduct[] = [
  {
    ...mockProducts[5],
    clearanceReason: 'surplus',
    clearanceDescription: 'ผลิตเกินจากออเดอร์โปรเจ็กต์ - 23 ชิ้น',
    clearanceEndDate: new Date('2024-12-17T23:59:59Z'),
    originalStock: 30,
    remainingStock: 23,
  },
];

// Mock User (สำหรับทดสอบ)
export const mockUser: User = {
  id: 1,
  email: 'test@example.com',
  firstName: 'สมชาย',
  lastName: 'ใจดี',
  phone: '+66812345678',
  role: 'customer',
  createdAt: new Date('2024-01-01'),
};
